### PR TITLE
Fix README

### PR DESCRIPTION
**Pull request by ashes999**

### CODE REVIEW

**Comment by ashes999** [comment]
Review please @PythonWantsBoop / @severokST

**Comment by PythonWantsBoop** [comment]
Not much to review here. I'd say it's good to go.

**Comment by ashes999** [comment]
Merge please? :)

**Comment by ashes999** [comment]
Thanks for this. It's not that I can't merge it myself; rather, I want us to have a culture of reviewing/merging each other's code as part of the code review process.

**Pull request merged**
